import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Countdown from '@/components/Countdown'
import Cronometer from '@/components/Cronometer'
import CurrentClock from '@/components/CurrentClock'
import { Suspense } from 'react';


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <Suspense>
          <Countdown duration={60 * 60 * 1000} />
          <CurrentClock />
          <Cronometer />
        </Suspense>
      </main>
    </>
  )
}
